using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEngine;
using UnityEngine.UI;

public class DeviceController : MonoBehaviour
{

    // Start is called before the first frame update
    void Start()
    {
        Button button = this.transform.Find("Button").GetComponent<Button>();
        button.onClick.AddListener(() =>
        {
            UIManager.ShowHomePanel();
        });
    }

    // Update is called once per frame
    void Update()
    {

    }
}
