using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class UserInfoController : PFUIPanel
{
    // Start is called before the first frame update
    protected override void Start()
    {
        this.transform.localPosition = new Vector3(0, 0, 0);

        Button exitBtn = this.transform.Find("InfoPanel").Find("Button").GetComponent<Button>();

        exitBtn.onClick.AddListener(() =>
        {
            UIManager.ShowHomePanel();
        });

        Button editBtn = this.transform.Find("InfoPanel").Find("EditButton").GetComponent<Button>();
        editBtn.onClick.AddListener(() =>
        {
            UIManager.ShowEditUserPanel();
        });
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
