using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class UserInfoController : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        this.transform.localPosition = new Vector3(0, 0, 0);

        Button exitBtn = this.transform.Find("InfoPanel").Find("Button").GetComponent<Button>();

        exitBtn.onClick.AddListener(() =>
        {
            UIManager.ShowHomePanel();
        });
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
