using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MainController : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        UIManager.Instance.MainPanel = (GameObject)this.transform.Find("Panel").gameObject;
        UIManager.Instance.ModalsPanel = this.transform.Find("PanelModals").gameObject;
        

        //MainMenu.transform.Find("Home").GetComponent<Button>().onClick.AddListener(() =>
        //{
        //    UIManager.ShowHomePanel();
        //});

        UIManager.ShowHomePanel();
        //UIManager.ShowUserInfoPanel();
        //UIManager.ShowEditUserPanel();
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
